### ISSUE TITLE
Some bugs in serialize()

### ISSUE THREAD

**Issue by ibc** [versatica/rtp.js#13]
### 1. Bug in `ByePacket`

```diff
diff --git a/src/tests/rtcp/ByePacket.test.ts b/src/tests/rtcp/ByePacket.test.ts
index e1e18a3..4c57510 100644
--- a/src/tests/rtcp/ByePacket.test.ts
+++ b/src/tests/rtcp/ByePacket.test.ts
@@ -76,6 +76,7 @@ describe('parse RTCP Bye packet', () =>
 		expect(packet.getSsrcs()).toEqual([ ssrc1, ssrc2 ]);
 		expect(packet.getReason()).toBe(reason);
 		expect(packet.needsSerialization()).toBe(false);
+		packet.serialize();
 		expect(areDataViewsEqual(packet.getView(), view2)).toBe(true);
 	});
```

```
$ DEBUG="*rtp*" npx jest --testPathPattern src/tests/rtcp/ByePacket.test.ts
  console.info
      rtp.js:utils areDataViewsEqual() | different byte [idx:27, view1:4, view2:0] +0ms

      at Logger.debug (node_modules/debug/src/common.js:113:10)

  console.info
      rtp.js:utils areDataViewsEqual() | view1: DataView {
      byteLength: 32,
      byteOffset: 0,
      buffer: ArrayBuffer {
        [Uint8Contents]: <a2 cb 00 07 62 42 76 e0 26 24 67 0e 0e 48 61 73 74 61 20 6c 61 20 76 69 73 74 61 04 00 00 00 00>,
        byteLength: 32
      }
    } +20ms

      at Logger.debug (node_modules/debug/src/common.js:113:10)

  console.info
      rtp.js:utils areDataViewsEqual() | view2: DataView {
      byteLength: 32,
      byteOffset: 0,
      buffer: ArrayBuffer {
        [Uint8Contents]: <a2 cb 00 07 62 42 76 e0 26 24 67 0e 0e 48 61 73 74 61 20 6c 61 20 76 69 73 74 61 00 00 00 00 04>,
        byteLength: 32
      }
    } +3ms
```

### 2. Bug in `ReceiverReportPacket`

```diff
diff --git a/src/tests/rtcp/ReceiverReportPacket.test.ts b/src/tests/rtcp/ReceiverReportPacket.test.ts
index 92692e6..120108c 100644
--- a/src/tests/rtcp/ReceiverReportPacket.test.ts
+++ b/src/tests/rtcp/ReceiverReportPacket.test.ts
@@ -114,6 +114,7 @@ describe('parse RTCP Receiver Report packet', () =>
 		expect(packet.getCount()).toBe(1);
 		expect(packet.getPadding()).toBe(4);
 		expect(packet.getSsrc()).toBe(0x5d931534);
+		packet.serialize();
 		expect(areDataViewsEqual(packet.getView(), view2)).toBe(true);
 
 		const report = packet.getReports()[0];
```

```
RangeError: computed packet length (32 bytes) is different than the available buffer size (36 bytes)
```

### 3. Bug in `SenderReportPacket`

```diff
diff --git a/src/tests/rtcp/SenderReportPacket.test.ts b/src/tests/rtcp/SenderReportPacket.test.ts
index d773ed8..36250c4 100644
--- a/src/tests/rtcp/SenderReportPacket.test.ts
+++ b/src/tests/rtcp/SenderReportPacket.test.ts
@@ -115,6 +115,7 @@ describe('parse RTCP Sender Report packet', () =>
 		expect(packet.getRtpTimestamp()).toBe(rtpTimestamp);
 		expect(packet.getPacketCount()).toBe(packetCount);
 		expect(packet.getOctetCount()).toBe(octetCount);
+		packet.serialize();
 		expect(areDataViewsEqual(packet.getView(), view2)).toBe(true);
 	});
 ```

```
RangeError: computed packet length (28 bytes) is different than the available buffer size (32 bytes)
```

**Comment by ibc** [comment]
Issue 1 fixed here: https://github.com/versatica/rtp.js/commit/26c5f64202c28e022d4670b0ab6918314d6f142f

**Comment by ibc** [comment]
Issue 2 fixed here: https://github.com/versatica/rtp.js/commit/3c4585432f776a4e13ab70c7c2c31305ee65e77a
